### ISSUE TITLE
Docutils error on MacOSX

### ISSUE THREAD

**Issue by tundish** [tundish/addisonarches#3]
Task exception was never retrieved
future: <Task finished coro=<__call__() done, defined at /Users/dave/ref/addisonarches/addisonarches/game.py:425> exception=AttributeError("'Namespace' object has no attribute 'character_level_inline_markup'",)>
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/Users/dave/ref/addisonarches/addisonarches/game.py", line 448, in __call__
    folder, self.ensemble, self.dialogueQueue, loop=loop)
  File "/Users/dave/py3.5-media/lib/python3.5/site-packages/turberfield/dialogue/viewer.py", line 107, in run_through
    with script as dialogue:
  File "/Users/dave/py3.5-media/lib/python3.5/site-packages/turberfield/dialogue/model.py", line 208, in __enter__
    self.doc = self.read(script.read())
  File "/Users/dave/py3.5-media/lib/python3.5/site-packages/turberfield/dialogue/model.py", line 199, in read
    parser.parse(text, doc)
  File "/Users/dave/py3.5-media/lib/python3.5/site-packages/docutils/parsers/rst/__init__.py", line 185, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/Users/dave/py3.5-media/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 157, in run
    inliner.init_customizations(document.settings)
  File "/Users/dave/py3.5-media/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 470, in init_customizations
    if settings.character_level_inline_markup:
AttributeError: 'Namespace' object has no attribute 'character_level_inline_markup'

**Comment by tundish** [comment]
docutils==0.13.1
